export const ANIME_LIST_REQUEST = "ANIME_LIST_REQUEST"
export const ANIME_LIST_SUCCESS = "ANIME_LIST_SUCCESS"
export const ANIME_LIST_FAIL = "ANIME_LIST_FAIL"

export const ANIME_ADD_REQUEST = "ANIME_ADD_REQUEST"
export const ANIME_ADD_SUCCESS = "ANIME_ADD_SUCCESS"
export const ANIME_ADD_FAIL = "ANIME_ADD_FAIL"

export const ANIME_UPDATE_SUCCESS = "ANIME_UPDATE_SUCCESS"

export const ANIME_DELETE_SUCCESS = "ANIME_DELETE_SUCCESS"